globs:
  - "**/*.md"
ignores:
  - "website/node_modules/**"
  - "website/.next/**"
  - ".flox/run/**"
  - ".flox/cache/**"
  - ".flox/lib/**"
  - ".flox/log/**"
  - "coverage.out"
config:
  MD013: false
  MD033: false
