repos:
  - repo: local
    hooks:
      - id: ares-ci
        name: ares local CI
        entry: scripts/pre-commit.sh
        language: system
        pass_filenames: false
        stages: [pre-commit]
